FROM python:3.10.4

MAINTAINER Ian Hoyt-McCulllough <ianiac@email.unc.edu>

LABEL io.k8s.description="Script to fetch data from FIMAN API" \
 io.k8s.display-name="sdfp-get-fiman-data" \
 io.openshift.expose-services="5432:http"

WORKDIR /code

COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY . .


ENV POSTGRESQL_PASSWORD=apassword
ENV POSTGRESQL_USER=postgres
ENV POSTGRESQL_DATABASE=postgres
ENV POSTGRESQL_HOSTNAME='172.17.0.2'
ENV FIMAN_URL='http://199.90.60.180:8080/OneRain/DataAPI?method=GetSensorData&system_key=319f3adb-d66f-4f25-8dc6-14a11215132f'

USER 1001
EXPOSE 5432

ENTRYPOINT ["python"]
CMD ["get-data.py"]